### ISSUE TITLE
Is it possible to add a feature to skip some stories ?

### ISSUE THREAD

**Issue by udiedrichsen** [storybooks/storyshots#43]
I really like storyshots 👍 

It would to great if its possible to mark some stories. So that these stories are ignored by
storyshots. During the normal work are some components changing very often, but
other one are pretty stable. I suggest something:

storiesOf('Test', module)
  .ignoreStoryshots()
  .add( .... )

and for some stories "storyshots" just throws an error:
✗ Profile: ERROR
  TypeError: (0 , _reactDom.unstable_renderSubtreeIntoContainer) is not a function
      at RenderToLayer.renderLayer (...

**Comment by arunoda** [comment]
Hey, we can't have an API in the storybook for this.
But we already have a solution.

Check the [-g and -x options](https://github.com/kadirahq/storyshots/blob/master/src/cli.js#L22).

**Comment by udiedrichsen** [comment]
Great 👍 
Works perfect 💯 

E.g:
npm run --silent storyshots -x '^_X_'

I just miss one think in the test summary:
Test Summary

> 9 stories tested.
> 9/9 stories matched with snapshots.

just a wish :-)

> 4 stories ignored 

Storybook is just amazing and together with storyshoot a dream team.
Thanks for this toolkit 👍

**Comment by roonyh** [comment]
@udiedrichsen, Created a new issue to track that: #44

About the error: At the moment storyshots cannot work with stories that access `reactDom` because of an compatibility between react-test-render and react-dom. If a component you are using from a library calls `reactDom`'s methods then storyshots might give errors. Some of them will be fixed when we update react to 15.4.
